#!/bin/bash

BATCHSIZE=5
BAR_CHAR='|'
EMPTY_CHAR=' '

BAR_WIDTH=50
PREFIX='['
SUFFIX=']'

progress_bar_draw() {
  local current=$1
  local length=$2
  local perc_done=$((current * 100 / length))
  local num_bars=$((perc_done * BAR_WIDTH / 100))

  local s_out

  local bar=$(printf "%*s" "$num_bars" "" | tr ' ' "$BAR_CHAR")
  local empty=$(printf "%*s" "$((BAR_WIDTH - num_bars))" "" | tr ' ' "$EMPTY_CHAR")
  local s_stats="$current/$length ($perc_done%%)"
  s_out="$PREFIX$bar$empty$SUFFIX $s_stats"

  printf "\r%s" "$s_out"
}

process_item() {
  sleep .01
  # echo Processing item
}

init_term() {
  printf "Init term"
  # save cursor position
  # add blank line
  # set margins
  # restore cursor position
}
deinit_term() {
  printf "Deinit term"
  # save cursor location
  # set cursor position
  # clear line
  # set margins
  # restore cursor
}

main() {

  shopt checkwinsize
  (:)

  trap deinit_term EXIT
  trap init_term WINCH

  init_term

  local i=0
  local length=500

  printf "Batchsize set to: %d\n" "$BATCHSIZE"
  printf "Length set to: %d\n" "$length"

  for ((i = 0; i < length; i += BATCHSIZE)); do
    # echo "Loop iteration: i=$i"
    progress_bar_draw "$((i + 1))" "$length"
    process_item
  done
}

main "$@"
